# https://docs.directus.io/self-hosted/docker-guide.html
version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
      # - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql # setting up a database
    networks:
      - directus
    env_file: ./myenv.env

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8056:8056
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    env_file: ./myenv.env
      # Make sure to set this in production
      # (see https://docs.directus.io/self-hosted/config-options#general)

networks:
  directus:
